# sweep_config.yaml
program: main_hpo.py
method: bayes  # Can be 'grid', 'random', 'bayes'
project: SVR_hpo

# Metric to optimize
metric:
  goal: maximize
  name: custom_score

# Parameters to sweep over
parameters:
  gamma1:
    values: [0.05, 0.1, 0.2]
  gamma2:
    values: [0.2, 0.5, 0.7]  
  gamma3:
    values: [0.1, 0.5, 1]

# For continuous ranges, you can also use:
# parameters:
#   gamma1:
#     distribution: uniform
#     min: 0.05
#     max: 0.2
#   gamma2:
#     distribution: uniform
#     min: 0.2
#     max: 0.7
#   gamma3:
#     distribution: uniform
#     min: 0.1
#     max: 1.0

# Early stopping (optional)
early_terminate:
  type: hyperband
  min_iter: 100
  eta: 3

# Run configuration
name: gamma_optimization_sweep
description: "Hyperparameter optimization for gamma1, gamma2, gamma3 parameters"