optimization_metric: density_range
bandwidth: 1
k_neighbors: 100
plot: True
save_model: trained_kde
save_results: results.pkl

data_path: /abiomed/intermediate_data_d4rl/farama_sac_expert/Walker2d-v2_obs_noisy_0.005_1.0.pkl
env: Walker2d-v2

transition: True

