optimization_metric: density_range
bandwidth: 1
k_neighbors: 100
plot: True
save_model: trained_kde
save_results: results.pkl

env: Walker2d-v2
data_path: /abiomed/intermediate_data_d4rl/farama_sac_expert/Walker2d-v2_expert_1086.pkl
