env: Walker2d-v2
model_name_rl: bc
seed: 1
eval_episodes: 100
data_path: "/abiomed/intermediate_data_d4rl/farama_sac_expert/Walker2d-v2_obs_noisy_0.005_1.0.pkl"

transition: True
noise_rate_transition: 1.0
scale_transition: 0.005

