env: HalfCheetah-v2
seed: 1
eval_episodes: 10
data_path: "/abiomed/intermediate_data_d4rl/farama_tqc_expert/HalfCheetah-v2_action_obs_noisy_0.01_0.5_0.005_1.0.pkl"
max_timesteps: 1000000

transition: True
noise_rate_transition: 1.0
scale_transition: 0.005
batch_size: 128
action: True
noise_rate_action: 0.5
scale_action: 0.01
alpha: 0.02

classifier_model_name: HalfCheetah-v2/trained_kde_action_obs