env: HalfCheetah-v2
seed: 1
eval_episodes: 10
max_timesteps: 1000000
data_path: "/abiomed/intermediate_data_d4rl/farama_tqc_expert/HalfCheetah-v2_expert_1086.pkl"
alpha: 0.02
classifier_model_name: HalfCheetah-v2/trained_kde