env: Walker2d-v2
seed: 1
eval_episodes: 10
max_timesteps: 1000000
data_path: "/abiomed/intermediate_data_d4rl/farama_sac_expert/Walker2d-v2_expert_1086.pkl"
alpha: 0.02
classifier_model_name: Walker2d-v2/trained_kde