_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 55
                - 100
            "2":
                - 1
                - 55
                - 100
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
env:
    value: abiomed
gamma1:
    value: 0.05
gamma2:
    value: 0.2
gamma3:
    value: 0.5
seed:
    value: 1
trial_id:
    value: 1
