env: HalfCheetah-v2
model_name_rl: svr
seed: 1
eval_episodes: 100
data_path: "/abiomed/intermediate_data_d4rl/farama_tqc_expert/HalfCheetah-v2_action_obs_noisy_0.01_0.5_0.005_1.0.pkl"

transition: True
noise_rate_transition: 1.0
scale_transition: 0.005

action: True
noise_rate_action: 0.5
scale_action: 0.01
