env: HalfCheetah-v2
model_name_rl: svr
seed: 1
eval_episodes: 100
data_path: "/abiomed/intermediate_data_d4rl/farama_tqc_expert/HalfCheetah-v2_action_noisy_0.08_1.0.pkl"

action: True
noise_rate_action: 1.0
scale_action: 0.08
