env: abiomed
seed: 1
eval_episodes: 10
eval_freq: 10000
alpha: 0.006
sample_std: 0.5
no_normalize: True
max_timesteps: 200000
data_path: "/abiomed/offline_datasets/SAC_exp_5000eps_stochastic_noise0.80_scale0.20.pkl"
