env: Hopper-v2
seed: 1
eval_episodes: 10
max_timesteps: 1000000
data_path: "/abiomed/intermediate_data_d4rl/farama_sac_expert/Hopper-v2_action_noisy_0.08_1.0.pkl"

action: True
noise_rate_action: 1.0
scale_action: 0.08

alpha: 0.02
