env: abiomed
no_normalize: True
eval_data: 0.1
seed: 1
num_iters: 20000
data_path: "/abiomed/offline_datasets/SAC_exp_5000eps_stochastic_noise0.80_scale0.20.npz"
noise_rate: 0.8
noise_scale: 0.2
gamma1: 0.2
gamma2: 0.5
gamma3: 1.0
